# Neovim plugins available in nixpkgs.
{ pkgs, inputs }:

with pkgs.vimPlugins;
[
  image-nvim
  astrotheme
  rainbow-delimiters-nvim
  luasnip
  grug-far-nvim
  telescope-nvim
  telescope-sg
  telescope-undo-nvim
  telescope-hierarchy-nvim
  glance-nvim
  vim-terminator
  git-blame-nvim
  lsp-colors-nvim
  nvim-lspconfig
  blink-cmp
  friendly-snippets
  nvim-treesitter
  gitsigns-nvim
  nui-nvim
  neogit
  conjure
  vim-illuminate
  iron-nvim
  treesj
  persistent-breakpoints-nvim
  bufferline-nvim
  git-conflict-nvim
  toggleterm-nvim
  treewalker-nvim
  go-nvim
  snacks-nvim
  trouble-nvim
  which-key-nvim
  nvim-parinfer
  vim-sexp
  vim-sexp-mappings-for-regular-people
  mason-nvim-dap-nvim
  nvim-dap-rr
  nvim-hlslens
  nvim-lightbulb
  nvim-dap-go
  lsp-inlayhints-nvim
  neotest-vitest
  tssorter-nvim
  nvim-dap
  nvim-dap-python
  nvim-dap-virtual-text
  nvim-jdtls
  neotest-haskell
  lsp-status-nvim
  plenary-nvim
  lualine-nvim
  neo-tree-nvim
  neotest
  neotest-go
  neotest-jest
  neotest-playwright
  nvim-nio
  telescope-fzf-native-nvim
  telescope-symbols-nvim
  telescope-ui-select-nvim
  nvim-web-devicons
  lspsaga-nvim
  none-ls-nvim
  lspkind-nvim
  typescript-tools-nvim
  tiny-glimmer-nvim
  vim-dispatch
  vim-dispatch-neovim
  nvim-dap-ui
  neotest-java
  crates-nvim
  nvim-metals
  diffview-nvim
  smear-cursor-nvim
  conform-nvim
  overseer-nvim
  vim-floaterm
  mason-lspconfig-nvim
  mason-nvim
  nvim-autopairs
  nvim-ts-autotag
  pretty-fold-nvim
  fold-preview-nvim
  nvim-vtsls
  nvim-treesitter-context
]
++ import ./flake-plugins.nix { inherit pkgs inputs; }
